name: Workflow1
on:
  workflow_dispatch:
    inputs:
      workflow2_name:
        description: 'Workflow2 Name for Triggering'
        required: true
        default: 'Workflow2'
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: test
          run: |
            sudo apt install sshpass
            echo installedsshpass
            sshpass -p password ssh 87.79.240.210
