name: Remote update execution
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 87.79.240.210
        username: max
        key: ${{ secrets.SSH_KEY }}
        script: |
                    bash /home/max/update.sh
